//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyD_P3Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERACION
    {
        public int cod_operacion { get; set; }
        public string tipo { get; set; }
        public string no_cuenta { get; set; }
        public Nullable<decimal> monto { get; set; }
        public string descripcion { get; set; }
        public int cod_usuario { get; set; }
    }
}
