//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyD_P2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CITA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CITA()
        {
            this.HISTORIAL = new HashSet<HISTORIAL>();
        }
    
        public int id_cita { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> fecha { get; set; }
        public string hora { get; set; }
        public int paciente { get; set; }
        public int personal { get; set; }
        public int sala { get; set; }

        public IEnumerable<System.Web.Mvc.SelectListItem> ListaPersonal { get; set; }
        public IEnumerable<System.Web.Mvc.SelectListItem> ListaSala { get; set; }
        public IEnumerable<System.Web.Mvc.SelectListItem> ListaPaciente { get; set; }


        public virtual PACIENTE PACIENTE1 { get; set; }
        public virtual PERSONAL PERSONAL1 { get; set; }
        public virtual SALA SALA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL> HISTORIAL { get; set; }
    }
}
